enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Revanced Extended Khinda"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"                                                   
excluded-patches = "'Alternative thumbnails' 'Change start page' 'Custom branding name for YouTube' 'Custom double tap length' 'Disable auto audio tracks' 'Disable splash animation' 'Enable debug logging' 'Layout switch' 'Spoof app version' 'Spoof client' 'Translations for YouTube'"                                                 
included-patches = "'Force hide player buttons background' 'Hide Shorts dimming' 'Hide animated button background' 'Hide double tap overlay filter' 'MaterialYou' 'Visual preferences icons'"                                                 
version = "auto"                                                      
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx-khinda"
